# Generated by Django 5.0.3 on 2024-07-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presignedurl',
            name='expiry_time',
            field=models.DateTimeField(default='2000-01-01 00:00:00.00000+00.00'),
        ),
    ]
